### ISSUE TITLE
Error at getLastRelease

### ISSUE THREAD

**Issue by felixfbecker** [felipecrs/semantic-release-vsce#6]
```
[Semantic release]: Load plugin semantic-release-vsce
[Semantic release]: Load plugin @semantic-release/github
[Semantic release]: Load plugin semantic-release-vsce
[Semantic release]: Load plugin semantic-release-vsce
[Semantic release]: Load plugin @semantic-release/github
[Semantic release]: Run automated release for branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for vsce
[Semantic release]: Call plugin get-last-release
[Semantic release]: Lookup extension details for "felixfbecker.php-intellisense".
[Semantic release]: Found version [object Object] of package felixfbecker.php-intellisense
[Semantic release]: An error occurred while running semantic-release: Error: The "getLastRelease" plugin output if defined, must be an object with an optionnal valid semver version in the "version" property.. Received: { version: 
   { version: '2.0.1',
     flags: 'validated',
     lastUpdated: '2017-11-19T02:45:21.723Z' } }
    at Object.getLastRelease (/home/travis/build/felixfbecker/vscode-php-intellisense/node_modules/semantic-release/lib/plugins/normalize.js:30:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by felixfbecker** [comment]
https://travis-ci.org/felixfbecker/vscode-php-intellisense/builds/306094364

**Comment by raix** [comment]
should be fixed in https://github.com/raix/semantic-release-vsce/commit/adf57493901f1452991b6f753b70060d84cd3e61

**Comment by felixfbecker** [comment]
Verified!

**Comment by raix** [comment]
Cool - @felixfbecker did you test the whole flow? *(I haven't had time to actually test it...)*

**Comment by felixfbecker** [comment]
I added it to a couple of projects and they all detect correctly that they should not release ;)
I have not yet made a change to an extension that actually triggered a release. Will report any issue if I meet that - I think if we verified that once we could bump to 1.0.0.
